const QuizActionTypes = {
    FETCH_QUESTIONS_START: "FETCH_QUESTIONS_START",
    FETCH_QUESTIONS_SUCCESS: "FETCH_QUESTIONS_SUCCESS",
    FETCH_QUESTIONS_FAILURE: "FETCH_QUESTIONS_FAILURE",
    ADD_FAVORITE: "ADD_FAVORITE",
    DELETE_FAVORITE: "DELETE_FAVORITE"
};
export default QuizActionTypes;